### ISSUE TITLE
Pass conformance tests

### ISSUE THREAD

**Issue by lifthrasiir** [lifthrasiir/j40#1]
libjxl has a battery of [conformance tests](https://github.com/libjxl/conformance), which is expected to become ISO/IEC 18181-3 in the future. They are coarser-grained tests and not suitable for detailed testing or estimating the actual progress, but they represent a good milestone so will be tracked here.

* [ ] alpha_nonpremultiplied
* [ ] alpha_premultiplied
* [x] alpha_triangle
* [ ] animation_icos4D
* [ ] animation_newtons_cradle
* [ ] animation_spline
* [ ] bench_oriented_BRG
* [ ] bicycles
* [ ] bike
* [ ] blendmodes
* [ ] cafe
* [ ] cmyk_layers
* [ ] delta_palette
    * Decodes but incorrect
* [ ] grayscale
    * Fails before `TODO` is reached
* [ ] grayscale_jpeg
    * Memory corruption
* [ ] grayscale_public_university
* [ ] lossless_pfm
* [ ] lz77_flower
    * Decodes and almost correct but has a subtle intensity difference
* [ ] noise
* [ ] opsin_inverse
    * Decodes but incorrect
* [ ] patches
* [ ] patches_lossless
* [ ] progressive
* [ ] spot
* [ ] sunset_logo
* [ ] upsampling
